### ISSUE TITLE
AttributeError: <plugin> object has no attribute 'analyze_string'

### ISSUE THREAD

**Issue by aleveille** [pmarlow/ci_secrets#7]
In the required dependency `detect-secrets`, the method `analyze_string` was renamed to `analyze_line` ([ref](https://github.com/Yelp/detect-secrets/commit/0c9e97e96bcc715b340bc8d7df3ce1bfbf6be1de#diff-8cb91032a37e1bcf2fd0f3a8643c8b6d)) causing the following error in `ci_secrets`

```
ci_secrets --since $(git merge-base HEAD origin/master) --log INFO
/usr/local/lib/python3.7/site-packages/ci_secrets/main.py:14: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = yaml.load(ymlfile)
[main]	INFO	Found common ancestors: COMMIT-SHA-REDACTED
[main]	INFO	********************COMMIT-SHA-REDACTED********************
[main]	INFO	********************COMMIT-SHA-REDACTED********************
Traceback (most recent call last):
  File "/usr/local/bin/ci_secrets", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/ci_secrets/main.py", line 55, in main
    finding_count += check_commit_for_secrets(commit, args.include_delete, plugins)
  File "/usr/local/lib/python3.7/site-packages/ci_secrets/main.py", line 78, in check_commit_for_secrets
    finding_count += check_diff_for_secrets(diff.diff, commit.hexsha, plugins)
  File "/usr/local/lib/python3.7/site-packages/ci_secrets/main.py", line 84, in check_diff_for_secrets
    return _scan_string(diff_string, plugins, commit_sha)
  File "/usr/local/lib/python3.7/site-packages/ci_secrets/main.py", line 90, in _scan_string
    results = plugin.analyze_string(line,0,'does not matter')
AttributeError: 'Base64HighEntropyString' object has no attribute 'analyze_string'
```

**Comment by aleveille** [comment]
@pmarlow can you please have a look (PR attached to the issue)?

**Comment by clementnero** [comment]
@pmarlow, any update on this issue ?

**Comment by aleveille** [comment]
Last attempt to get @pmarlow attention on this

**Comment by aleveille** [comment]
Closing and unsubscribring.
